# signal/config/default.toml

# Signal servisinin kendi SIP (UDP) sunucusu ayarları
[sip]
host = "0.0.0.0"
port = 5060
# Bu IP adresi, SDP ve Contact başlıklarında dış dünyaya anons edilecektir.
# Yerel test için 127.0.0.1, sunucu için sunucunun Public IP adresi olmalıdır.
public_ip = "127.0.0.1"

# Bağlanacağı core servisinin adresi
[core]
address = "http://127.0.0.1:50051"